// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOWqfIXjTUsw-_4XhlYjLm5hnonbzpqXs',
    appId: '1:9105005440:web:a2fa53b537e6600ebe7f65',
    messagingSenderId: '9105005440',
    projectId: 'stewyrt-11',
    authDomain: 'stewyrt-11.firebaseapp.com',
    storageBucket: 'stewyrt-11.firebasestorage.app',
    measurementId: 'G-E1GVVK9BHD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANmaWmTwYTC43VuiYP4JadOqRh_aLp9rw',
    appId: '1:9105005440:android:8b3e913cac5c391cbe7f65',
    messagingSenderId: '9105005440',
    projectId: 'stewyrt-11',
    storageBucket: 'stewyrt-11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_AAvr9QPj5nW8grtvDA8KSDynGSgCZbE',
    appId: '1:9105005440:ios:ae5dd89ec831d95fbe7f65',
    messagingSenderId: '9105005440',
    projectId: 'stewyrt-11',
    storageBucket: 'stewyrt-11.firebasestorage.app',
    iosBundleId: 'com.stewyrt.stewyrt',
  );

}